import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryClientProviderWrapper from "./query-client";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProviderWrapper>
        <body className={inter.className + " bg-gray-950"}>{children}</body>
      </QueryClientProviderWrapper>
    </html>
  );
}
